spring:
  data:
    redis:
      host: localhost
      port: 6379
      username: ""
      password: ""
      ssl:
        enabled: false
  kafka:
    bootstrap-servers: "localhost:9092"
    properties:
      "[schema.registry.url]": "http://localhost:8081"
    consumer:
      key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
      value-deserializer: "io.confluent.kafka.serializers.KafkaAvroDeserializer"
      properties:
        "[specific.avro.reader]": "false"

logging:
  level:
    com.harpreetsaund: DEBUG